name: Create Release and Document

on:
  push:
    tags:
      - '*' # Trigger on all tag

jobs:
  call-doc-generator:
    # Grant permissions for the job to create a release
    permissions:
      contents: write

    # Correctly call the reusable workflow by providing the full path
    # Make sure 'generate-doc.yml' is the correct filename in your central repo
    uses: samah603/demo-generate-doc/.github/workflows/generate-doc.yml@demo

    with:
      # Pass the tag name as the 'version' input
      # version: ${{ github.ref_name }}
      changelog: ${{ github.event.release.body }}

    # Pass down the GITHUB_TOKEN and any other secrets automatically
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
